image: python:latest

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - build
  - test

pytest:
  stage: test
  script:
    - pytest --cov-report term-missing --cov=course_project/ tests
  artifacts:
    when: always
    reports:
      junit: report.xml